kind: pipeline
name: default
workspace:
  base: /go
  path: src/github.com/petergreen86/go-drone-hello-world
steps:
  - name: test
    image: golang
    commands:
      - go get
      - go test
  - name: build
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output
  - name: run
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output
      - ./output
  - name: hub
    commands:
      - wget https://blackducksoftware.github.io/hub-detect/hub-detect.sh
      - chmod +x hub-detect.sh
      - ./hub-detect.sh --blackduck.hub.url=((hub_url)) --blackduck.hub.username=((hub_username)) --blackduck.hub.password=((hub_password))
